# Generated by Django 5.2.8 on 2025-12-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
