# Generated by Django 5.2.8 on 2026-01-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='is_review',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
