# Generated by Django 5.2.8 on 2026-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questionattempt_is_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='review_state',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
