# Generated by Django 5.2.8 on 2026-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quizattempt_review_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
