# Generated by Django 5.2.8 on 2026-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_questionattempt_is_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='review_state',
            field=models.BooleanField(default=None),
        ),
    ]
