# Generated by Django 5.2.8 on 2025-12-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
