# Generated by Django 5.2.8 on 2026-01-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quizattempt_review_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='review_state',
            field=models.BooleanField(default=False),
        ),
    ]
