# Generated by Django 5.2.8 on 2026-01-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_quizattempt_review_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='is_review',
        ),
    ]
