# Generated by Django 5.2.8 on 2025-12-06 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_key',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_str',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='question',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
