# Generated by Django 5.2.8 on 2025-12-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_question_answer_key_question_audio_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='word_scramble_direction',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
