# Generated by Django 5.2.8 on 2026-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_questionattempt_is_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
