# Generated by Django 5.2.8 on 2026-01-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quizattempt_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
    ]
