# Generated by Django 5.2.8 on 2026-01-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_quizattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
