# Generated by Django 5.2.8 on 2025-12-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_question_audio_str_alter_question_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_key',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
    ]
