# Generated by Django 5.2.8 on 2025-12-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='button_cloze_options',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
