# Generated by Django 5.2.8 on 2025-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_quizattempt_questionattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='question_id',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completion_status',
            field=models.CharField(default='completed', max_length=50),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='errorneous_questions',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
