# Generated by Django 5.2.8 on 2025-12-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_questionattempt_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='api.question'),
        ),
    ]
