# Generated by Django 5.2.8 on 2025-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_questionattempt_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='completion_status',
            field=models.CharField(default='uncompleted', max_length=50),
        ),
    ]
