# Generated by Django 5.2.8 on 2025-12-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_quizattempt_completion_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='question_exhausted',
            new_name='questions_exhausted',
        ),
    ]
