# Generated by Django 5.2.8 on 2025-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_question_exhausted_quizattempt_questions_exhausted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='error_flag',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
