# Generated by Django 5.2.8 on 2025-12-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_questionattempt_error_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='errorneous_questions',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
