# Generated by Django 5.2.8 on 2025-12-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_quizattempt_errorneous_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='questions_exhausted',
        ),
    ]
