# Generated by Django 5.2.8 on 2025-12-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_quizattempt_questions_exhausted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='word_scramble_direction',
        ),
    ]
