# Generated by Django 5.2.8 on 2025-12-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_level_category_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.category'),
        ),
    ]
