# Generated by Django 5.2.8 on 2025-12-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_unit_sub_category_unit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.level'),
        ),
    ]
